qt_add_resources(green "images"
    PREFIX "/"
    BASE assets
    FILES
        assets/icons/green.png
        assets/icons/production.png
        assets/icons/mac-production.png
        assets/svg/wallet-rename.svg
        assets/svg/wallet-settings.svg
        assets/svg/archive.svg
        assets/svg/unarchive.svg
        assets/svg/archived.svg
        assets/svg/3-dots.svg
        assets/svg/3-h-dots.svg
        assets/svg/btc-bg.svg
        assets/svg/2fa_email.svg
        assets/svg/2fa_gauth.svg
        assets/svg/2fa_general.svg
        assets/svg/2fa_phone.svg
        assets/svg/2fa_sms.svg
        assets/svg/2fa_telegram.svg
        assets/svg/about.svg
        assets/svg/abstract_background.svg
        assets/svg/account.svg
        assets/svg/add_wallet.svg
        assets/svg/add_wallet_1.svg
        assets/svg/addresses.svg
        assets/svg/advanced.svg
        assets/svg/amp.svg
        assets/svg/appsettings.svg
        assets/svg/arrow_left.svg
        assets/svg/arrow_right.svg
        assets/svg/assets.svg
        assets/svg/back_wallet.svg
        assets/svg/blockstream-logo.svg
        assets/svg/blockstream_jade.svg
        assets/svg/btc.svg
        assets/svg/btc_testnet.svg
        assets/svg/localtest.svg
        assets/svg/cancel.svg
        assets/svg/check.svg
        assets/svg/check-gray.svg
        assets/svg/coins.svg
        assets/svg/copy.svg
        assets/svg/down.svg
        assets/svg/electrum.svg
        assets/svg/erase.svg
        assets/svg/export.svg
        assets/svg/external_link.svg
        assets/svg/gearFill.svg
        assets/svg/generic_icon_30p.svg
        assets/svg/green_logo.svg
        assets/svg/green_server.svg
        assets/svg/grid.svg
        assets/svg/help.svg
        assets/svg/home.svg
        assets/svg/ic_done.svg
        assets/svg/info.svg
        assets/svg/jade_emblem_on_transparent_rgb.svg
        assets/svg/jade_logo_white_on_transparent_rgb.svg
        assets/svg/kebab.svg
        assets/svg/ledger-logo.svg
        assets/svg/ledger.svg
        assets/svg/ledger_nano_s.svg
        assets/svg/ledger_nano_x.svg
        assets/svg/liquid.svg
        assets/svg/logout.svg
        assets/svg/network.svg
        assets/svg/new.svg
        assets/svg/next.svg
        assets/svg/onboarding_write.svg
        assets/svg/overview.svg
        assets/svg/paste.svg
        assets/svg/plus.svg
        assets/svg/preferences.svg
        assets/svg/proxyV2.svg
        assets/svg/qr.svg
        assets/svg/qr_bg.svg
        assets/svg/qr_sweep.svg
        assets/svg/receive.svg
        assets/svg/received.svg
        assets/svg/recovery.svg
        assets/svg/refresh.svg
        assets/svg/right.svg
        assets/svg/search.svg
        assets/svg/security.svg
        assets/svg/send.svg
        assets/svg/sent.svg
        assets/svg/settings.svg
        assets/svg/settings_clicked.svg
        assets/svg/sidebar.svg
        assets/svg/stack_wallets.svg
        assets/svg/testnet-liquid.svg
        assets/svg/localtest-liquid.svg
        assets/svg/torV2.svg
        assets/svg/transactions.svg
        assets/svg/trezor.svg
        assets/svg/twofactor.svg
        assets/svg/tx-check.svg
        assets/svg/usbAlt.svg
        assets/svg/warning.svg
        assets/svg/warning_black.svg
        assets/svg/x.svg

        assets/png/jade_0.png
        assets/png/jade_1.png
        assets/png/jade_2.png
        assets/png/jade_3.png
        assets/png/jade_4.png
        assets/png/jade_5.png
        assets/png/jade_6.png
        assets/png/jade_7.png
        assets/png/jade2_0.png
        assets/png/jade2_1.png
        assets/png/jade2_2.png
        assets/png/jade2_3.png
        assets/png/jade2_4.png
        assets/png/jade2_5.png
        assets/png/jade2_6.png
        assets/png/jade2_7.png

        assets/png/jade_card.png
        assets/png/jade2_card.png

        assets/png/2fa_u2f.png
        assets/png/2fa_telegram.png

        assets/hints/jade_genuine.png

        assets/svg2/alert.svg
        assets/svg2/arrow_square_down.svg
        assets/svg2/arrow_right.svg
        assets/svg2/arrows-counter-clockwise.svg
        assets/svg2/back.svg
        assets/svg2/backspace.svg
        assets/svg2/bell.svg
        assets/svg2/beta.svg
        assets/svg2/blockstream-app.svg
        assets/svg2/bolt.svg
        assets/svg2/caret-down.svg
        assets/svg2/caret-down-white.svg
        assets/svg2/check.svg
        assets/svg2/check-green.svg
        assets/svg2/close.svg
        assets/svg2/close_black.svg
        assets/svg2/coin_selection.svg
        assets/svg2/copy.svg
        assets/svg2/copy-green.svg
        assets/svg2/copy2.svg
        assets/svg2/dots-three-green.svg
        assets/svg2/edit.svg
        assets/svg2/eject-simple-thin.svg
        assets/svg2/expand.svg
        assets/svg2/expired_2fa.svg
        assets/svg2/eye.svg
        assets/svg2/eye_closed.svg
        assets/svg2/flask.svg
        assets/svg2/gauge-green.svg
        assets/svg2/gear.svg
        assets/svg2/globe.svg
        assets/svg2/hand.svg
        assets/svg2/house.svg
        assets/svg2/import.svg
        assets/svg2/incoming.svg
        assets/svg2/info.svg
        assets/svg2/info_black.svg
        assets/svg2/info_red.svg
        assets/svg2/info_white.svg
        assets/svg2/jade-logo.svg
        assets/svg2/lightning.svg
        assets/svg2/list_bullets.svg
        assets/svg2/ledger-logo.svg
        assets/svg2/lock-simple-thin.svg
        assets/svg2/notifications.svg
        assets/svg2/tx-mixed.svg
        assets/svg2/multisig.svg
        assets/svg2/next_arrow.svg
        assets/svg2/onboard_background.svg
        assets/svg2/passphrase.svg
        assets/svg2/paste.svg
        assets/svg2/pencil-simple-line-green.svg
        assets/svg2/plugs_white.svg
        assets/svg2/printer.svg
        assets/svg2/qrcode.svg
        assets/svg2/refresh.svg
        assets/svg2/right.svg
        assets/svg2/search.svg
        assets/svg2/search_green.svg
        assets/svg2/singlesig.svg
        assets/svg2/signature-light.svg
        assets/svg2/share.svg
        assets/svg2/share-green.svg
        assets/svg2/shield_check.svg
        assets/svg2/shield_warning.svg
        assets/svg2/star.svg
        assets/svg2/star_white.svg
        assets/svg2/seal-check.svg
        assets/svg2/sun.svg
        assets/svg2/sun-dim.svg
        assets/svg2/trash.svg
        assets/svg2/tx-incoming.svg
        assets/svg2/tx-outgoing.svg
        assets/svg2/tx-redeposit.svg
        assets/svg2/wallet.svg
        assets/svg2/warning.svg
        assets/svg2/warning_black.svg
        assets/svg2/warning_white.svg
        assets/svg2/watermark_bitcoin.svg
        assets/svg2/watermark_liquid.svg
        assets/svg2/x-square.svg
        assets/svg2/x-circle.svg
        assets/svg2/zoom.svg
        assets/svg2/check-light.svg
        assets/svg2/fail-light.svg
        assets/svg2/warning-light.svg
        assets/svg2/help.svg
        assets/svg2/bug.svg
        assets/svg2/headset.svg
        assets/svg2/green-rebrand.svg

        assets/pdf/recovery-phrase-backup-template-12-words.pdf

        assets/svg2/amp_icon.svg
        assets/svg2/liquid_icon.svg

        assets/png/jade_genuine_1.png
        assets/png/jade_genuine_2.png

        assets/svg3/2fa_email.svg
        assets/svg3/2fa_expired.svg
        assets/svg3/2fa_gauth.svg
        assets/svg3/2fa_phone.svg
        assets/svg3/2fa_sms.svg
        assets/svg3/Authenticator.svg
        assets/svg3/Authenticator-2.svg
        assets/svg3/Authenticator-3.svg
        assets/svg3/Cancel.svg
        assets/svg3/Check.svg
        assets/svg3/Chip.svg
        assets/svg3/Desktop-Keys.svg
        assets/svg3/Globe.svg
        assets/svg3/Ledger.svg
        assets/svg3/Notifications.svg
        assets/svg3/Trade.svg
        assets/svg3/Wallet.svg
)

qt_add_resources(green "fonts"
    PREFIX "/"
    BASE assets
    FILES
        assets/fonts/monospace_bold.ttf
        assets/fonts/inter_regular.ttf
        assets/fonts/inter_extra_light.ttf
        assets/fonts/inter_thin.ttf
        assets/fonts/monospace_regular.ttf
        assets/fonts/inter_bold.ttf
)
