qt_add_resources(green "images"
    PREFIX "/"
    BASE assets
    FILES
        assets/icons/green.png
        assets/svg/wallet-rename.svg
        assets/svg/wallet-settings.svg
        assets/svg/archive.svg
        assets/svg/unarchive.svg
        assets/svg/archived.svg
        assets/svg/3-dots.svg
        assets/svg/3-h-dots.svg
        assets/svg/btc-bg.svg
        assets/svg/2fa_email.svg
        assets/svg/2fa_gauth.svg
        assets/svg/2fa_general.svg
        assets/svg/2fa_phone.svg
        assets/svg/2fa_sms.svg
        assets/svg/2fa_telegram.svg
        assets/svg/about.svg
        assets/svg/abstract_background.svg
        assets/svg/account.svg
        assets/svg/add_wallet.svg
        assets/svg/add_wallet_1.svg
        assets/svg/addresses.svg
        assets/svg/advanced.svg
        assets/svg/amp.svg
        assets/svg/appsettings.svg
        assets/svg/arrow_left.svg
        assets/svg/arrow_right.svg
        assets/svg/assets.svg
        assets/svg/back_wallet.svg
        assets/svg/blockstream-logo.svg
        assets/svg/blockstream_jade.svg
        assets/svg/btc.svg
        assets/svg/btc_testnet.svg
        assets/svg/localtest.svg
        assets/svg/cancel.svg
        assets/svg/check.svg
        assets/svg/check-gray.svg
        assets/svg/coins.svg
        assets/svg/copy.svg
        assets/svg/down.svg
        assets/svg/electrum.svg
        assets/svg/erase.svg
        assets/svg/export.svg
        assets/svg/external_link.svg
        assets/svg/gearFill.svg
        assets/svg/generic_icon_30p.svg
        assets/svg/green_logo.svg
        assets/svg/green_server.svg
        assets/svg/grid.svg
        assets/svg/help.svg
        assets/svg/home.svg
        assets/svg/ic_done.svg
        assets/svg/info.svg
        assets/svg/jade_emblem_on_transparent_rgb.svg
        assets/svg/jade_logo_white_on_transparent_rgb.svg
        assets/svg/kebab.svg
        assets/svg/key.svg
        assets/svg/ledger-logo.svg
        assets/svg/ledger.svg
        assets/svg/ledger_nano_s.svg
        assets/svg/ledger_nano_x.svg
        assets/svg/leftbar.svg
        assets/svg/liquid.svg
        assets/svg/logout.svg
        assets/svg/multi-sig.svg
        assets/svg/network.svg
        assets/svg/network_selector.svg
        assets/svg/network_selector_active.svg
        assets/svg/new.svg
        assets/svg/next.svg
        assets/svg/notifications.svg
        assets/svg/notifications_2.svg
        assets/svg/notifications_clicked.svg
        assets/svg/notifications_clicked_2.svg
        assets/svg/onboarding_illustration.svg
        assets/svg/onboarding_noonline.svg
        assets/svg/onboarding_noscrshot.svg
        assets/svg/onboarding_write.svg
        assets/svg/overview.svg
        assets/svg/paste.svg
        assets/svg/plus.svg
        assets/svg/preferences.svg
        assets/svg/proxyV2.svg
        assets/svg/qr.svg
        assets/svg/qr_bg.svg
        assets/svg/qr_sweep.svg
        assets/svg/receive.svg
        assets/svg/received.svg
        assets/svg/recovery.svg
        assets/svg/refresh.svg
        assets/svg/right.svg
        assets/svg/search.svg
        assets/svg/security.svg
        assets/svg/send.svg
        assets/svg/sent.svg
        assets/svg/settings.svg
        assets/svg/settings_clicked.svg
        assets/svg/sidebar.svg
        assets/svg/singleSig.svg
        assets/svg/stack_wallets.svg
        assets/svg/testnet-liquid.svg
        assets/svg/localtest-liquid.svg
        assets/svg/torV2.svg
        assets/svg/transactions.svg
        assets/svg/trezor.svg
        assets/svg/twofactor.svg
        assets/svg/tx-check.svg
        assets/svg/tx-spv-in-progress.svg
        assets/svg/tx-spv-not-longest.svg
        assets/svg/tx-spv-not-verified.svg
        assets/svg/tx-spv-verified.svg
        assets/svg/usbAlt.svg
        assets/svg/warning.svg
        assets/svg/warning_black.svg
        assets/svg/x.svg
        assets/png/lbtc.png
        assets/png/amp_background.png
        assets/png/liquid_background.png

        assets/hints/cpu.svg
        assets/hints/jade3d.svg

        assets/svg2/arrow_right.svg
        assets/svg2/back.svg
        assets/svg2/blockstream_green.svg
        assets/svg2/bolt.svg
        assets/svg2/btc_watermark.svg
        assets/svg2/check.svg
        assets/svg2/check-green.svg
        assets/svg2/close.svg
        assets/svg2/copy.svg
        assets/svg2/edit.svg
        assets/svg2/eye.svg
        assets/svg2/gear.svg
        assets/svg2/house.svg
        assets/svg2/next_arrow.svg
        assets/svg2/onboard_background.svg
        assets/svg2/printer.svg
        assets/svg2/refresh.svg
        assets/svg2/search.svg
        assets/svg2/shield_check.svg
        assets/svg2/shield_warning.svg
        assets/svg2/star.svg
        assets/svg2/take_control.svg
        assets/svg2/wallet.svg
        assets/svg2/warning.svg
)

qt_add_resources(green "fonts"
    PREFIX "/"
    BASE assets
    FILES
        assets/fonts/Roboto/Roboto-Medium.ttf
        assets/fonts/Roboto/Roboto-Light.ttf
        assets/fonts/Roboto/Roboto-Regular.ttf
        assets/fonts/Roboto/Roboto-MediumItalic.ttf
        assets/fonts/Roboto/Roboto-ThinItalic.ttf
        assets/fonts/Roboto/Roboto-BoldItalic.ttf
        assets/fonts/Roboto/Roboto-LightItalic.ttf
        assets/fonts/Roboto/Roboto-Italic.ttf
        assets/fonts/Roboto/Roboto-BlackItalic.ttf
        assets/fonts/Roboto/Roboto-Bold.ttf
        assets/fonts/Roboto/Roboto-Thin.ttf
        assets/fonts/Roboto/Roboto-Black.ttf
)
