qt_add_resources(${APP_TARGET} "qtquickcontrols2"
    PREFIX "/"
    BASE qml
    FILES
        qml/qtquickcontrols2.conf
        qml/+windows/qtquickcontrols2.conf
)

SET(QML_FILES
    qml/analytics.js
    qml/jade.js
    qml/util.js
    qml/GCard.qml
    qml/TwoFactorEnableDrawer.qml
    qml/DebugRectangle.qml
    qml/WalletGeneralSettingsView.qml
    qml/WalletsView.qml
    qml/TransactionView.qml
    qml/HSpacer.qml
    qml/WalletDialog.qml
    qml/StackViewPushAction.qml
    qml/SignLiquidTransactionResolverView.qml
    qml/GHeader.qml
    qml/Wallet2faSettingsView.qml
    qml/GComboBox.qml
    qml/GDropdown.qml
    qml/TwoFactorAuthExpiryDialog.qml
    qml/Tag.qml
    qml/AccountDelegate.qml
    qml/DeleteWalletDialog.qml
    qml/ChangePinDrawer.qml
    qml/MnemonicView.qml
    qml/TwoFactorLimitDrawer.qml
    qml/JadeSignMessageView.qml
    qml/MainMenuBar.qml
    qml/GTextField.qml
    qml/NLockTimeDialog.qml
    qml/GSwitch.qml
    qml/VSpacer.qml
    qml/AbstractDialog.qml
    qml/ControllerDialog.qml
    qml/WizardPage.qml
    qml/Spacer.qml
    qml/AssetDelegate.qml
    qml/RemoveWalletDialog.qml
    qml/DialogFooter.qml
    qml/OutputDelegate.qml
    qml/AnimLoader.qml
    qml/PreferencesDialog.qml
    qml/AssetDrawer.qml
    qml/AssetListView.qml
    qml/DescriptiveRadioButton.qml
    qml/SettingsPage.qml
    qml/CopyableLabel.qml
    qml/TransactionProgress.qml
    qml/QRCode.qml
    qml/JadeSignLiquidTransactionView.qml
    qml/GButton.qml
    qml/WordField.qml
    qml/WalletViewHeader.qml
    qml/AmountValidator.qml
    qml/DisableAllPinsDialog.qml
    qml/GPane.qml
    qml/main.qml
    qml/DialogHeader.qml
    qml/CancelTwoFactorResetDrawer.qml
    qml/GTextArea.qml
    qml/Collapsible.qml
    qml/ScannerPopup.qml
    qml/DeviceImage.qml
    qml/DeviceBadge.qml
    qml/SelectCoinsView.qml
    qml/TwoFactorDisableDrawer.qml
    qml/TransactionDelegate.qml
    qml/AnalyticsConsentPage.qml
    qml/JadeSignTransactionView.qml
    qml/SideBar.qml
    qml/AlertView.qml
    qml/WalletAdvancedSettingsView.qml
    qml/RequestTwoFactorResetDrawer.qml
    qml/EditableLabel.qml
    qml/FixedErrorBadge.qml
    qml/QRCodePopup.qml
    qml/ProgressIndicator.qml
    qml/ScannerView.qml
    qml/StatusBar.qml
    qml/PinView.qml
    qml/GFlickable.qml
    qml/TransactionStatusBadge.qml
    qml/PopupBalloon.qml
    qml/SectionLabel.qml
    qml/AddressDelegate.qml
    qml/Constants.qml
    qml/SettingsBox.qml
    qml/CoinDelegate.qml
    qml/MainPage.qml
    qml/OverviewPage.qml
    qml/SetRecoveryEmailDialog.qml
    qml/MainPageHeader.qml
    qml/LedgerSignTransactionView.qml
    qml/AssetIcon.qml
    qml/ProviderIcon.qml
    qml/AuthHandlerTaskView.qml
    qml/GetCredentialsView.qml
    qml/TaskDispatcherInspector.qml
    qml/TProgressBar.qml
    qml/TListView.qml
    qml/GMenu.qml
    qml/GStackView.qml
    qml/WalletDrawer.qml
    qml/CreateAccountDrawer.qml
    qml/ReceiveDrawer.qml
    qml/SendDrawer.qml
    qml/BackButton.qml
    qml/SendAccountAssetSelector.qml
    qml/AccountAssetField.qml
    qml/AddressField.qml
    qml/AmountField.qml
    qml/PrimaryButton.qml
    qml/RegularButton.qml
    qml/LinkButton.qml
    qml/CloseButton.qml
    qml/CopyAddressButton.qml
    qml/AssetField.qml
    qml/AssetSelector.qml
    qml/SearchField.qml
    qml/DrawerTitle.qml
    qml/FieldTitle.qml
    qml/CreateAccountPage.qml
    qml/SecurityPolicyButton.qml
    qml/WalletHeaderCard.qml
    qml/TotalBalanceCard.qml
    qml/CardBar.qml
    qml/BuyDrawer.qml
    qml/BuyPage.qml
    qml/BuyWebViewPage.qml
    qml/CountrySelectorPage.qml
    qml/QuotesListPage.qml
    qml/LineChart.qml
    qml/StackViewPage.qml
    qml/SelectRecoveryKeyPage.qml
    qml/MnemonicSizeSelector.qml
    qml/XPubField.qml
    qml/InfoCard.qml
    qml/PrintButton.qml
    qml/TermOfServicePage.qml
    qml/AddWalletPage.qml
    qml/MnemonicWarningsPage.qml
    qml/MnemonicBackupPage.qml
    qml/MnemonicCheckPage.qml
    qml/WalletView.qml
    qml/PinField.qml
    qml/PinLoginPage.qml
    qml/LoadingPage.qml
    qml/SetupPinPage.qml
    qml/RegisterPage.qml
    qml/RestorePage.qml
    qml/RestoreCheckPage.qml
    qml/WatchOnlyWalletPage.qml
    qml/MultisigWatchOnlyAddPage.qml
    qml/WatchOnlyLoginPage.qml
    qml/UsernameField.qml
    qml/PasswordField.qml
    qml/WatchOnlyNetworkPage.qml
    qml/AbstractDrawer.qml
    qml/WalletsDrawer.qml
    qml/AlreadyRestoredPage.qml
    qml/UseDevicePage.qml
    qml/ConnectJadePage.qml
    qml/JadePage.qml
    qml/JadeInitializedView.qml
    qml/JadeLoginView.qml
    qml/JadeUninitializedView.qml
    qml/JadeUnlockView.qml
    qml/JadeFirmwareConfigSelector.qml
    qml/ArchivedAccountsDrawer.qml
    qml/JadeNotificationDialog.qml
    qml/SendPage.qml
    qml/SendConfirmPage.qml
    qml/PinPadButton.qml
    qml/TransactionCompletedPage.qml
    qml/TransactionDetailsDrawer.qml
    qml/GStackLayout.qml
    qml/DeploymentDialog.qml
    qml/TaskPageFactory.qml
    qml/SignMessagePage.qml
    qml/AddressDetailsDrawer.qml
    qml/CircleButton.qml
    qml/ShareButton.qml
    qml/AddressDetailsPage.qml
    qml/DevicePage.qml
    qml/JadeDeviceDelegate.qml
    qml/JadeInstructionsView.qml
    qml/JadeCard.qml
    qml/DevicePromptView.qml
    qml/JadeBasicUpdateView.qml
    qml/JadeAdvancedUpdateView.qml
    qml/JadeConfirmUpdatePage.qml
    qml/JadeUpdateDialog2.qml
    qml/JadeVerifyAddressPage.qml
    qml/Hint.qml
    qml/SplashPage.qml
    qml/AppPage.qml
    qml/WalletOptionsButton.qml
    qml/SelectFeePage.qml
    qml/AssetDetailsPage.qml
    qml/AppBanner.qml
    qml/NotificationToast.qml
    qml/ConnectLedgerPage.qml
    qml/LedgerPage.qml
    qml/LedgerDeviceDelegate.qml
    qml/TTextField.qml
    qml/ReceiveAccountAssetSelector.qml
    qml/CompletedImage.qml
    qml/CanceledImage.qml
    qml/AddressVerifiedBadge.qml
    qml/NotificationsDrawer.qml
    qml/ErrorPage.qml
    qml/MultiImage.qml
    qml/TwoFactorEnableGenericView.qml
    qml/TwoFactorEnablePhoneView.qml
    qml/TwoFactorEnableGAuthPage.qml
    qml/SecureFundsPage.qml
    qml/JadeHttpRequestDialog.qml
    qml/LinkLabel.qml
    qml/PassphraseDialog.qml
    qml/SinglesigWatchOnlyAddPage.qml
    qml/WalletWatchOnlySettingsView.qml
    qml/JadeGetMasterBlindingKeyView.qml
    qml/StatusDrawer.qml
    qml/TwoFactorExpiredSelectAccountPage.qml
    qml/Bip21Footer.qml
    qml/TorFooter.qml
    qml/OutagePage.qml
    qml/RedepositPage.qml
    qml/RedepositConfirmPage.qml
    qml/RedepositLiquidPage.qml
    qml/RedepositLiquidConfirmPage.qml
    qml/Countries.qml
    qml/PhoneField.qml
    qml/UpdateUnspentsDrawer.qml
    qml/VFlickable.qml
    qml/JadeFirmwareUpdatedPage.qml
    qml/AddressLabel.qml
    qml/JadeGenuineCheckDialog.qml
    qml/PromoDrawer.qml
    qml/JadeGenuineCheckPage.qml
    qml/JadeGenuineCheckingPage.qml
    qml/PromoCard.qml
    qml/ReceivePage.qml
    qml/JadeDetailsDrawer.qml
    qml/HelpButton.qml
    qml/RequestSupportPage.qml
    qml/SupportSubmittedPage.qml
    qml/SupportDrawer.qml
    qml/AssetsView.qml
    qml/HomePage.qml
    qml/TransactionsPage.qml
    qml/SecurityPage.qml
    qml/FilterPopup.qml
    qml/AccountFilterPopup.qml
    qml/AssetFilterPopup.qml
    qml/AddressFilterPopup.qml
    qml/SelectAccountPage.qml
    qml/SendDetailsPage.qml
    qml/AccountSelectorPage.qml
    qml/AssetSelectorPage.qml
    qml/AccountAssetPage.qml
    qml/RightArrowIndicator.qml
    qml/PushButton.qml
    qml/ErrorPane.qml
    qml/BackupDrawer.qml
    qml/NotificationDrawer.qml
    qml/BackupPage.qml
    qml/AccountLabel.qml
    qml/AddressTypeLabel.qml
    qml/SetupWatchonlyDrawer.qml
    qml/TransactionAmounts.qml
)

if (GREEN_NO_RESOURCES)
    set(QML_FILES_2)
    target_compile_definitions(${APP_TARGET} PRIVATE SOURCE_DIR=${CMAKE_SOURCE_DIR})
else()
    set(QML_FILES_2 ${QML_FILES})
endif()

qt_policy(SET QTP0004 NEW)

qt_add_qml_module(${APP_TARGET}
    URI Blockstream.Green
    VERSION 1.0
    NO_PLUGIN
    DEPENDENCIES QtQuick
    SOURCES src/networkmanager.cpp
    QML_FILES ${QML_FILES_2}
    RESOURCE_PREFIX /
    #ENABLE_TYPE_COMPILER
    NO_CACHEGEN
    NO_LINT
)
