#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef UNIFFI_CPP_INTERNALSTRUCTS
#define UNIFFI_CPP_INTERNALSTRUCTS
struct ForeignBytes {
    int32_t len;
    uint8_t *data;
};

struct RustBuffer {
    uint64_t capacity;
    uint64_t len;
    uint8_t *data;
};

struct RustCallStatus {
    int8_t code;
    RustBuffer error_buf;
};

#endif
struct UniffiVTableCallbackInterfaceForeignStore {
    void * get;
    void * put;
    void * remove;
    void * uniffi_free;
};
struct UniffiVTableCallbackInterfaceLogging {
    void * log;
    void * uniffi_free;
};
void * uniffi_lwk_fn_clone_address(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_address(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_address_new(RustBuffer s, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_address_is_blinded(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_address_network(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_address_qr_code_text(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_address_qr_code_uri(void * ptr, RustBuffer pixel_per_module, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_address_script_pubkey(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_address_to_unconfidential(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_address_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_addressresult(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_addressresult(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_addressresult_address(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_addressresult_index(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp0(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp0(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_amp0_new(void * network, RustBuffer username, RustBuffer password, RustBuffer amp_id, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp0_address(void * ptr, RustBuffer index, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp0_amp_id(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_amp0_last_index(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp0_sign(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp0_wollet_descriptor(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp0connected(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp0connected(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_amp0connected_new(void * network, void * signer_data, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp0connected_get_challenge(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp0connected_login(void * ptr, RustBuffer sig, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp0loggedin(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp0loggedin(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp0loggedin_create_amp0_account(void * ptr, uint32_t pointer, RustBuffer account_xpub, RustCallStatus *out_status);
void uniffi_lwk_fn_method_amp0loggedin_create_watch_only(void * ptr, RustBuffer username, RustBuffer password, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp0loggedin_get_amp_ids(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_amp0loggedin_next_account(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp0pset(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp0pset(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_amp0pset_new(void * pset, RustBuffer blinding_nonces, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp0pset_blinding_nonces(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp0pset_pset(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp0signerdata(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp0signerdata(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp0signerdata_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp2(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp2(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_amp2_new(RustBuffer server_key, RustBuffer url, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_amp2_new_testnet(RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp2_cosign(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp2_descriptor_from_str(void * ptr, RustBuffer keyorigin_xpub, RustBuffer descriptor_blinding_key, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp2_register_wallet(void * ptr, void * desc, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_amp2descriptor(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_amp2descriptor(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_amp2descriptor_descriptor(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_amp2descriptor_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_anyclient(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_anyclient(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_anyclient_from_electrum(void * client, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_anyclient_from_esplora(void * client, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_assetamount(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_assetamount(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_assetamount_amount(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_assetamount_asset(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_assetblindingfactor(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_assetblindingfactor(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_assetblindingfactor_from_bytes(RustBuffer bytes, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_assetblindingfactor_from_string(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_assetblindingfactor_zero(RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_assetblindingfactor_to_bytes(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_assetblindingfactor_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_bip(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_bip(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bip_new_bip49(RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bip_new_bip84(RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bip_new_bip87(RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_bip21(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_bip21(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bip21_new(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_bip21_address(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_amount(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_as_str(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_label(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_lightning(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_message(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_offer(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_payjoin(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_bip21_payjoin_output_substitution(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip21_silent_payment_address(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_bip321(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_bip321(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bip321_new(RustBuffer s, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_amount(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_ark(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_as_str(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_label(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_lightning(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_message(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_offer(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_payjoin(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_bip321_payjoin_output_substitution(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bip321_silent_payment_address(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_bitcoinaddress(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_bitcoinaddress(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bitcoinaddress_new(RustBuffer s, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_bitcoinaddress_is_mainnet(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bitcoinaddress_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_blockheader(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_blockheader(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_blockheader_block_hash(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_blockheader_height(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_blockheader_merkle_root(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_blockheader_prev_blockhash(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_blockheader_time(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_blockheader_version(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_bolt11invoice(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_bolt11invoice(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_bolt11invoice_new(RustBuffer s, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_amount_milli_satoshis(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_bolt11invoice_expiry_time(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_invoice_description(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_bolt11invoice_min_final_cltv_expiry_delta(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_network(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_payee_pub_key(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_payment_hash(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_payment_secret(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_bolt11invoice_timestamp(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_bolt11invoice_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_boltzsession(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_boltzsession(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_boltzsession_from_builder(RustBuffer builder, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_boltzsession_new(void * network, void * client, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_btc_to_lbtc(void * ptr, uint64_t amount, void * refund_address, void * claim_address, RustBuffer webhook, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_completed_swap_ids(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_fetch_bolt12_invoice(void * ptr, void * lightning_payment, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_fetch_swaps_info(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_get_swap_data(void * ptr, RustBuffer swap_id, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_invoice(void * ptr, uint64_t amount, RustBuffer description, void * claim_address, RustBuffer webhook, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_lbtc_to_btc(void * ptr, uint64_t amount, void * refund_address, void * claim_address, RustBuffer webhook, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_boltzsession_next_index_to_use(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_pending_swap_ids(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_prepare_pay(void * ptr, void * lightning_payment, void * refund_address, RustBuffer webhook, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_quote(void * ptr, uint64_t send_amount, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_quote_receive(void * ptr, uint64_t receive_amount, RustCallStatus *out_status);
void uniffi_lwk_fn_method_boltzsession_refresh_swap_info(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_boltzsession_remove_swap(void * ptr, RustBuffer swap_id, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_rescue_file(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_restorable_btc_to_lbtc_swaps(void * ptr, void * swap_list, void * claim_address, void * refund_address, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_restorable_lbtc_to_btc_swaps(void * ptr, void * swap_list, void * claim_address, void * refund_address, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_restorable_reverse_swaps(void * ptr, void * swap_list, void * claim_address, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_boltzsession_restorable_submarine_swaps(void * ptr, void * swap_list, void * refund_address, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_restore_invoice(void * ptr, RustBuffer data, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_restore_lockup(void * ptr, RustBuffer data, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_restore_prepare_pay(void * ptr, RustBuffer data, RustCallStatus *out_status);
void uniffi_lwk_fn_method_boltzsession_set_next_index_to_use(void * ptr, uint32_t next_index_to_use, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_boltzsession_swap_restore(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_contract(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_contract(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_contract_new(RustBuffer domain, RustBuffer issuer_pubkey, RustBuffer name, uint8_t precision, RustBuffer ticker, uint8_t version, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_contract_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_currencycode(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_currencycode(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_currencycode_new(RustBuffer alpha3, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_currencycode_alpha3(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_currencycode_exp(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_currencycode_name(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_currencycode_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_currencycode_uniffi_trait_eq_eq(void * ptr, void * other, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_currencycode_uniffi_trait_eq_ne(void * ptr, void * other, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_currencycode_uniffi_trait_hash(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_electrumclient(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_electrumclient(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_electrumclient_from_url(RustBuffer electrum_url, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_electrumclient_new(RustBuffer electrum_url, int8_t tls, int8_t validate_domain, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_electrumclient_broadcast(void * ptr, void * tx, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_electrumclient_full_scan(void * ptr, void * wollet, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_electrumclient_full_scan_to_index(void * ptr, void * wollet, uint32_t index, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_electrumclient_get_tx(void * ptr, void * txid, RustCallStatus *out_status);
void uniffi_lwk_fn_method_electrumclient_ping(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_electrumclient_tip(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_esploraclient(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_esploraclient(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_esploraclient_from_builder(RustBuffer builder, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_esploraclient_new(RustBuffer url, void * network, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_esploraclient_new_waterfalls(RustBuffer url, void * network, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_esploraclient_broadcast(void * ptr, void * tx, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_esploraclient_full_scan(void * ptr, void * wollet, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_esploraclient_full_scan_to_index(void * ptr, void * wollet, uint32_t index, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_esploraclient_tip(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_externalutxo(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_externalutxo(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_externalutxo_from_unchecked_data(void * outpoint, void * txout, void * unblinded, uint32_t max_weight_to_satisfy, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_externalutxo_new(uint32_t vout, void * tx, void * unblinded, uint32_t max_weight_to_satisfy, int8_t is_segwit, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_foreignstore(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_foreignstore(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_init_callback_vtable_foreignstore(const UniffiVTableCallbackInterfaceForeignStore & vtable);
RustBuffer uniffi_lwk_fn_method_foreignstore_get(void * ptr, RustBuffer key, RustCallStatus *out_status);
void uniffi_lwk_fn_method_foreignstore_put(void * ptr, RustBuffer key, RustBuffer value, RustCallStatus *out_status);
void uniffi_lwk_fn_method_foreignstore_remove(void * ptr, RustBuffer key, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_foreignstorelink(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_foreignstorelink(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_foreignstorelink_new(void * store, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_invoice(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_invoice(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_invoice_amount_sats(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoice_bolt11_invoice(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoice_bolt12_invoice(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_invoice_is_bolt11(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_invoice_is_bolt12(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoice_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_invoiceresponse(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_invoiceresponse(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_advance(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_invoiceresponse_bolt11_invoice(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_boltz_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_claim_txid(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_invoiceresponse_complete_pay(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_lockup_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_serialize(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_invoiceresponse_swap_id(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_issuance(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_issuance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_issuance_asset(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_issuance_asset_satoshi(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_issuance_is_confidential(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_issuance_is_issuance(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_issuance_is_null(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_issuance_is_reissuance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_issuance_prev_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_issuance_prev_vout(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_issuance_token(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_issuance_token_satoshi(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_lightningpayment(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_lightningpayment(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_lightningpayment_from_bolt11_invoice(void * invoice, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_lightningpayment_new(RustBuffer s, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lightningpayment_bolt11_invoice(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lightningpayment_bolt12_invoice_amount(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_lightningpayment_bolt12_offer_has_amount(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lightningpayment_description(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_lightningpayment_is_bolt12(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_lightningpayment_set_bolt12_invoice_amount(void * ptr, uint64_t amount_sats, RustCallStatus *out_status);
void uniffi_lwk_fn_method_lightningpayment_set_bolt12_invoice_amount_via_items(void * ptr, uint64_t items, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_lockupresponse(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_lockupresponse(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_advance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_boltz_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_chain_from(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_chain_to(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_claim_address(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_claim_txid(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_lockupresponse_complete(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_lockupresponse_expected_amount(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_lockup_address(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_lockup_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_refund_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_serialize(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_lockupresponse_set_lockup_txid(void * ptr, RustBuffer txid, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_swap_id(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lockupresponse_uri(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_logging(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_logging(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_init_callback_vtable_logging(const UniffiVTableCallbackInterfaceLogging & vtable);
void uniffi_lwk_fn_method_logging_log(void * ptr, RustBuffer level, RustBuffer message, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_logginglink(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_logginglink(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_logginglink_new(void * logging, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_lwktestenv(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_lwktestenv(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_lwktestenv_new(RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lwktestenv_electrum_url(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lwktestenv_esplora_url(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_lwktestenv_generate(void * ptr, uint32_t blocks, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lwktestenv_genesis_block_hash(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_lwktestenv_get_new_address(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_lwktestenv_height(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lwktestenv_issue_asset(void * ptr, uint64_t satoshi, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_lwktestenv_network(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_lwktestenv_send_to_address(void * ptr, void * address, uint64_t satoshi, RustBuffer asset, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lwktestenv_waterfalls_url(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_lwkteststore(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_lwkteststore(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_lwkteststore_new(void * store, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_lwkteststore_read(void * ptr, RustBuffer key, RustCallStatus *out_status);
void uniffi_lwk_fn_method_lwkteststore_remove(void * ptr, RustBuffer key, RustCallStatus *out_status);
void uniffi_lwk_fn_method_lwkteststore_write(void * ptr, RustBuffer key, RustBuffer value, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_mnemonic(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_mnemonic(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_mnemonic_from_entropy(RustBuffer b, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_mnemonic_from_random(uint8_t word_count, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_mnemonic_new(RustBuffer s, RustCallStatus *out_status);
uint8_t uniffi_lwk_fn_method_mnemonic_word_count(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_mnemonic_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_network(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_network(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_network_mainnet(RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_network_regtest(RustBuffer policy_asset, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_network_regtest_default(RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_network_testnet(RustCallStatus *out_status);
void * uniffi_lwk_fn_method_network_default_electrum_client(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_network_default_esplora_client(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_network_genesis_block_hash(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_network_is_mainnet(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_network_policy_asset(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_network_tx_builder(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_network_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_network_uniffi_trait_eq_eq(void * ptr, void * other, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_network_uniffi_trait_eq_ne(void * ptr, void * other, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_network_uniffi_trait_hash(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_outpoint(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_outpoint(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_outpoint_from_parts(void * txid, uint32_t vout, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_outpoint_new(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_outpoint_txid(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_outpoint_vout(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_outpoint_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_payment(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_payment(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_payment_new(RustBuffer s, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_bip21(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_bip321(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_bip353(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_bitcoin_address(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_payment_fetch_lnurl_invoice(void * ptr, RustBuffer info, uint64_t amount_sats, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_kind(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_lightning_invoice(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_lightning_offer(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_lightning_payment(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_liquid_address(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_liquid_bip21(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_lnurl(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_payment_resolve_bip353(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_payment_resolve_lnurl_info(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_posconfig(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_posconfig(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_posconfig_decode(RustBuffer encoded, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_posconfig_new(void * descriptor, void * currency, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_posconfig_with_options(void * descriptor, void * currency, RustBuffer show_gear, RustBuffer show_description, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_posconfig_currency(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_posconfig_descriptor(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_posconfig_encode(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_posconfig_show_description(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_posconfig_show_gear(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_posconfig_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_posconfig_uniffi_trait_eq_eq(void * ptr, void * other, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_posconfig_uniffi_trait_eq_ne(void * ptr, void * other, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_posconfig_uniffi_trait_hash(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_precision(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_precision(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_precision_new(uint8_t precision, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_precision_sats_to_string(void * ptr, int64_t sats, RustCallStatus *out_status);
int64_t uniffi_lwk_fn_method_precision_string_to_sats(void * ptr, RustBuffer val, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_preparepayresponse(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_preparepayresponse(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_advance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_boltz_fee(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_preparepayresponse_complete_pay(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_lockup_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_refund_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_serialize(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_preparepayresponse_set_lockup_txid(void * ptr, RustBuffer txid, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_swap_id(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_preparepayresponse_uri(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_preparepayresponse_uri_address(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_preparepayresponse_uri_amount(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_pset(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_pset(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_pset_new(RustBuffer base64, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_pset_combine(void * ptr, void * other, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_pset_extract_tx(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_pset_finalize(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_pset_inputs(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_pset_outputs(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_pset_unique_id(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_pset_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_psetbalance(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_psetbalance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetbalance_balances(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_psetbalance_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetbalance_recipients(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_psetdetails(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_psetdetails(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_psetdetails_balance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetdetails_fingerprints_has(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetdetails_fingerprints_missing(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetdetails_inputs_issuances(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetdetails_signatures(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_psetinput(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_psetinput(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetinput_issuance(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetinput_issuance_asset(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetinput_issuance_ids(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetinput_issuance_token(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetinput_previous_script_pubkey(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_psetinput_previous_txid(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_psetinput_previous_vout(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetinput_redeem_script(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_psetinput_sighash(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_psetoutput(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_psetoutput(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetoutput_amount(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetoutput_asset(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetoutput_blinder_index(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_psetoutput_script_pubkey(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_psetsignatures(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_psetsignatures(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetsignatures_has_signature(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_psetsignatures_missing_signature(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_quotebuilder(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_quotebuilder(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_quotebuilder_build(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_quotebuilder_receive(void * ptr, RustBuffer asset, RustCallStatus *out_status);
void uniffi_lwk_fn_method_quotebuilder_send(void * ptr, RustBuffer asset, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_recipient(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_recipient(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_recipient_address(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_recipient_asset(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_recipient_value(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_recipient_vout(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_script(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_script(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_script_empty(RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_script_from_bytes(RustBuffer bytes, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_script_from_string(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_script_new(RustBuffer hex, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_script_new_op_return(RustBuffer data, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_script_bytes(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_script_is_provably_unspendable(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_script_jet_sha256_hex(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_script_to_asm(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_script_to_bytes(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_script_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_secretkey(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_secretkey(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_secretkey_from_bytes(RustBuffer bytes, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_secretkey_from_wif(RustBuffer wif, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_secretkey_bytes(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_secretkey_sign(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_signer(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_signer(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_signer_new(void * mnemonic, void * network, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_signer_random(void * network, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_signer_amp0_account_xpub(void * ptr, uint32_t account, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_signer_amp0_sign_challenge(void * ptr, RustBuffer challenge, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_signer_amp0_signer_data(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_signer_derive_bip85_mnemonic(void * ptr, uint32_t index, uint32_t word_count, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_signer_fingerprint(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_signer_keyorigin_xpub(void * ptr, void * bip, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_signer_mnemonic(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_signer_sign(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_signer_singlesig_desc(void * ptr, RustBuffer script_variant, RustBuffer blinding_variant, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_signer_wpkh_slip77_descriptor(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_swaplist(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_swaplist(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_swaplist_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_transaction(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_transaction(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_transaction_from_bytes(RustBuffer bytes, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_transaction_from_string(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_transaction_new(RustBuffer hex, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_transaction_bytes(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_transaction_discount_vsize(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_transaction_fee(void * ptr, RustBuffer policy_asset, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_transaction_inputs(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_transaction_outputs(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_transaction_to_bytes(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_transaction_txid(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_transaction_verify_tx_amt_proofs(void * ptr, RustBuffer utxos, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_transaction_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_txbuilder(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_txbuilder(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_txbuilder_new(void * network, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_add_burn(void * ptr, uint64_t satoshi, RustBuffer asset, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_add_explicit_recipient(void * ptr, void * address, uint64_t satoshi, RustBuffer asset, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_add_external_utxos(void * ptr, RustBuffer utxos, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_add_input_rangeproofs(void * ptr, int8_t add_rangeproofs, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_add_lbtc_recipient(void * ptr, void * address, uint64_t satoshi, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_add_recipient(void * ptr, void * address, uint64_t satoshi, RustBuffer asset, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_drain_lbtc_to(void * ptr, void * address, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_drain_lbtc_wallet(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_fee_rate(void * ptr, RustBuffer rate, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_txbuilder_finish(void * ptr, void * wollet, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_txbuilder_finish_for_amp0(void * ptr, void * wollet, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_issue_asset(void * ptr, uint64_t asset_sats, RustBuffer asset_receiver, uint64_t token_sats, RustBuffer token_receiver, RustBuffer contract, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_liquidex_make(void * ptr, void * utxo, void * address, uint64_t amount, RustBuffer asset, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_liquidex_take(void * ptr, RustBuffer proposals, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_reissue_asset(void * ptr, RustBuffer asset_to_reissue, uint64_t satoshi_to_reissue, RustBuffer asset_receiver, RustBuffer issuance_tx, RustCallStatus *out_status);
void uniffi_lwk_fn_method_txbuilder_set_wallet_utxos(void * ptr, RustBuffer utxos, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txbuilder_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_txin(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_txin(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_txin_outpoint(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_txin_sequence(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_txout(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_txout(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_txout_from_explicit(void * script_pubkey, RustBuffer asset_id, uint64_t satoshi, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txout_asset(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_txout_is_fee(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_txout_is_partially_blinded(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_txout_script_pubkey(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_txout_unblind(void * ptr, void * secret_key, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txout_unconfidential_address(void * ptr, void * network, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txout_value(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_txoutsecrets(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_txoutsecrets(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txoutsecrets_asset(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txoutsecrets_asset_bf(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txoutsecrets_asset_commitment(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_txoutsecrets_is_explicit(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_txoutsecrets_value(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txoutsecrets_value_bf(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txoutsecrets_value_commitment(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_txid(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_txid(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_txid_from_bytes(RustBuffer bytes, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_txid_from_string(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_txid_new(RustBuffer hex, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txid_bytes(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txid_to_bytes(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_txid_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_unvalidatedliquidexproposal(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_unvalidatedliquidexproposal(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_unvalidatedliquidexproposal_from_pset(void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_unvalidatedliquidexproposal_new(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_unvalidatedliquidexproposal_insecure_validate(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_unvalidatedliquidexproposal_needed_tx(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_unvalidatedliquidexproposal_validate(void * ptr, void * previous_tx, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_unvalidatedliquidexproposal_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_update(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_update(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_update_new(RustBuffer bytes, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_update_only_tip(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_update_serialize(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_validatedliquidexproposal(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_validatedliquidexproposal(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_validatedliquidexproposal_input(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_validatedliquidexproposal_output(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_validatedliquidexproposal_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_valueblindingfactor(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_valueblindingfactor(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_valueblindingfactor_from_bytes(RustBuffer bytes, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_valueblindingfactor_from_string(RustBuffer s, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_valueblindingfactor_zero(RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_valueblindingfactor_to_bytes(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_valueblindingfactor_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_wallettx(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_wallettx(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_balance(void * ptr, RustCallStatus *out_status);
uint64_t uniffi_lwk_fn_method_wallettx_fee(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_height(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_inputs(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_outputs(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_timestamp(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wallettx_tx(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wallettx_txid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_type_(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettx_unblinded_url(void * ptr, RustBuffer explorer_url, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_wallettxout(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_wallettxout(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wallettxout_address(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettxout_ext_int(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wallettxout_height(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wallettxout_outpoint(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wallettxout_script_pubkey(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wallettxout_unblinded(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_wallettxout_wildcard_index(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_webhook(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_webhook(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_webhook_new(RustBuffer url, RustBuffer status, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_wollet(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_wollet(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_wollet_new(void * network, void * descriptor, RustBuffer datadir, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_wollet_with_custom_store(void * network, void * descriptor, void * store, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_add_details(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_address(void * ptr, RustBuffer index, RustCallStatus *out_status);
void uniffi_lwk_fn_method_wollet_apply_transaction(void * ptr, void * tx, RustCallStatus *out_status);
void uniffi_lwk_fn_method_wollet_apply_update(void * ptr, void * update, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_balance(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_descriptor(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_dwid(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_extract_wallet_utxos(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_finalize(void * ptr, void * pset, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_wollet_is_amp0(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_wollet_is_segwit(void * ptr, RustCallStatus *out_status);
uint32_t uniffi_lwk_fn_method_wollet_max_weight_to_satisfy(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_pset_details(void * ptr, void * pset, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_transaction(void * ptr, void * txid, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_transactions(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_transactions_paginated(void * ptr, uint32_t offset, uint32_t limit, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_txos(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_unblind_utxos_with(void * ptr, void * blinding_privkey, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wollet_utxos(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wollet_wait_for_tx(void * ptr, void * txid, void * client, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_wolletbuilder(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_wolletbuilder(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_wolletbuilder_new(void * network, void * descriptor, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wolletbuilder_build(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_method_wolletbuilder_utxo_only(void * ptr, int8_t utxo_only, RustCallStatus *out_status);
void uniffi_lwk_fn_method_wolletbuilder_with_legacy_fs_store(void * ptr, RustBuffer datadir, RustCallStatus *out_status);
void uniffi_lwk_fn_method_wolletbuilder_with_merge_threshold(void * ptr, RustBuffer merge_threshold, RustCallStatus *out_status);
void * uniffi_lwk_fn_clone_wolletdescriptor(void * ptr, RustCallStatus *out_status);
void uniffi_lwk_fn_free_wolletdescriptor(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_constructor_wolletdescriptor_new(RustBuffer descriptor, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wolletdescriptor_derive_blinding_key(void * ptr, void * script_pubkey, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_wolletdescriptor_is_amp0(void * ptr, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_method_wolletdescriptor_is_mainnet(void * ptr, RustCallStatus *out_status);
void * uniffi_lwk_fn_method_wolletdescriptor_script_pubkey(void * ptr, RustBuffer ext_int, uint32_t index, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wolletdescriptor_url_encoded_descriptor(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_method_wolletdescriptor_uniffi_trait_display(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_func_derive_asset_id(void * txin, void * contract, RustCallStatus *out_status);
RustBuffer uniffi_lwk_fn_func_derive_token_id(void * txin, void * contract, RustCallStatus *out_status);
int8_t uniffi_lwk_fn_func_is_provably_segwit(void * script_pubkey, RustBuffer redeem_script, RustCallStatus *out_status);
RustBuffer ffi_lwk_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status);
RustBuffer ffi_lwk_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status);
void ffi_lwk_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status);
RustBuffer ffi_lwk_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status);
uint16_t uniffi_lwk_checksum_func_derive_asset_id();
uint16_t uniffi_lwk_checksum_func_derive_token_id();
uint16_t uniffi_lwk_checksum_func_is_provably_segwit();
uint16_t uniffi_lwk_checksum_method_address_is_blinded();
uint16_t uniffi_lwk_checksum_method_address_network();
uint16_t uniffi_lwk_checksum_method_address_qr_code_text();
uint16_t uniffi_lwk_checksum_method_address_qr_code_uri();
uint16_t uniffi_lwk_checksum_method_address_script_pubkey();
uint16_t uniffi_lwk_checksum_method_address_to_unconfidential();
uint16_t uniffi_lwk_checksum_method_addressresult_address();
uint16_t uniffi_lwk_checksum_method_addressresult_index();
uint16_t uniffi_lwk_checksum_method_amp0_address();
uint16_t uniffi_lwk_checksum_method_amp0_amp_id();
uint16_t uniffi_lwk_checksum_method_amp0_last_index();
uint16_t uniffi_lwk_checksum_method_amp0_sign();
uint16_t uniffi_lwk_checksum_method_amp0_wollet_descriptor();
uint16_t uniffi_lwk_checksum_method_amp0connected_get_challenge();
uint16_t uniffi_lwk_checksum_method_amp0connected_login();
uint16_t uniffi_lwk_checksum_method_amp0loggedin_create_amp0_account();
uint16_t uniffi_lwk_checksum_method_amp0loggedin_create_watch_only();
uint16_t uniffi_lwk_checksum_method_amp0loggedin_get_amp_ids();
uint16_t uniffi_lwk_checksum_method_amp0loggedin_next_account();
uint16_t uniffi_lwk_checksum_method_amp0pset_blinding_nonces();
uint16_t uniffi_lwk_checksum_method_amp0pset_pset();
uint16_t uniffi_lwk_checksum_method_amp2_cosign();
uint16_t uniffi_lwk_checksum_method_amp2_descriptor_from_str();
uint16_t uniffi_lwk_checksum_method_amp2_register_wallet();
uint16_t uniffi_lwk_checksum_method_amp2descriptor_descriptor();
uint16_t uniffi_lwk_checksum_method_assetamount_amount();
uint16_t uniffi_lwk_checksum_method_assetamount_asset();
uint16_t uniffi_lwk_checksum_method_assetblindingfactor_to_bytes();
uint16_t uniffi_lwk_checksum_method_bip21_address();
uint16_t uniffi_lwk_checksum_method_bip21_amount();
uint16_t uniffi_lwk_checksum_method_bip21_as_str();
uint16_t uniffi_lwk_checksum_method_bip21_label();
uint16_t uniffi_lwk_checksum_method_bip21_lightning();
uint16_t uniffi_lwk_checksum_method_bip21_message();
uint16_t uniffi_lwk_checksum_method_bip21_offer();
uint16_t uniffi_lwk_checksum_method_bip21_payjoin();
uint16_t uniffi_lwk_checksum_method_bip21_payjoin_output_substitution();
uint16_t uniffi_lwk_checksum_method_bip21_silent_payment_address();
uint16_t uniffi_lwk_checksum_method_bip321_amount();
uint16_t uniffi_lwk_checksum_method_bip321_ark();
uint16_t uniffi_lwk_checksum_method_bip321_as_str();
uint16_t uniffi_lwk_checksum_method_bip321_label();
uint16_t uniffi_lwk_checksum_method_bip321_lightning();
uint16_t uniffi_lwk_checksum_method_bip321_message();
uint16_t uniffi_lwk_checksum_method_bip321_offer();
uint16_t uniffi_lwk_checksum_method_bip321_payjoin();
uint16_t uniffi_lwk_checksum_method_bip321_payjoin_output_substitution();
uint16_t uniffi_lwk_checksum_method_bip321_silent_payment_address();
uint16_t uniffi_lwk_checksum_method_bitcoinaddress_is_mainnet();
uint16_t uniffi_lwk_checksum_method_blockheader_block_hash();
uint16_t uniffi_lwk_checksum_method_blockheader_height();
uint16_t uniffi_lwk_checksum_method_blockheader_merkle_root();
uint16_t uniffi_lwk_checksum_method_blockheader_prev_blockhash();
uint16_t uniffi_lwk_checksum_method_blockheader_time();
uint16_t uniffi_lwk_checksum_method_blockheader_version();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_amount_milli_satoshis();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_expiry_time();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_invoice_description();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_min_final_cltv_expiry_delta();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_network();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_payee_pub_key();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_payment_hash();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_payment_secret();
uint16_t uniffi_lwk_checksum_method_bolt11invoice_timestamp();
uint16_t uniffi_lwk_checksum_method_boltzsession_btc_to_lbtc();
uint16_t uniffi_lwk_checksum_method_boltzsession_completed_swap_ids();
uint16_t uniffi_lwk_checksum_method_boltzsession_fetch_bolt12_invoice();
uint16_t uniffi_lwk_checksum_method_boltzsession_fetch_swaps_info();
uint16_t uniffi_lwk_checksum_method_boltzsession_get_swap_data();
uint16_t uniffi_lwk_checksum_method_boltzsession_invoice();
uint16_t uniffi_lwk_checksum_method_boltzsession_lbtc_to_btc();
uint16_t uniffi_lwk_checksum_method_boltzsession_next_index_to_use();
uint16_t uniffi_lwk_checksum_method_boltzsession_pending_swap_ids();
uint16_t uniffi_lwk_checksum_method_boltzsession_prepare_pay();
uint16_t uniffi_lwk_checksum_method_boltzsession_quote();
uint16_t uniffi_lwk_checksum_method_boltzsession_quote_receive();
uint16_t uniffi_lwk_checksum_method_boltzsession_refresh_swap_info();
uint16_t uniffi_lwk_checksum_method_boltzsession_remove_swap();
uint16_t uniffi_lwk_checksum_method_boltzsession_rescue_file();
uint16_t uniffi_lwk_checksum_method_boltzsession_restorable_btc_to_lbtc_swaps();
uint16_t uniffi_lwk_checksum_method_boltzsession_restorable_lbtc_to_btc_swaps();
uint16_t uniffi_lwk_checksum_method_boltzsession_restorable_reverse_swaps();
uint16_t uniffi_lwk_checksum_method_boltzsession_restorable_submarine_swaps();
uint16_t uniffi_lwk_checksum_method_boltzsession_restore_invoice();
uint16_t uniffi_lwk_checksum_method_boltzsession_restore_lockup();
uint16_t uniffi_lwk_checksum_method_boltzsession_restore_prepare_pay();
uint16_t uniffi_lwk_checksum_method_boltzsession_set_next_index_to_use();
uint16_t uniffi_lwk_checksum_method_boltzsession_swap_restore();
uint16_t uniffi_lwk_checksum_method_currencycode_alpha3();
uint16_t uniffi_lwk_checksum_method_currencycode_exp();
uint16_t uniffi_lwk_checksum_method_currencycode_name();
uint16_t uniffi_lwk_checksum_method_electrumclient_broadcast();
uint16_t uniffi_lwk_checksum_method_electrumclient_full_scan();
uint16_t uniffi_lwk_checksum_method_electrumclient_full_scan_to_index();
uint16_t uniffi_lwk_checksum_method_electrumclient_get_tx();
uint16_t uniffi_lwk_checksum_method_electrumclient_ping();
uint16_t uniffi_lwk_checksum_method_electrumclient_tip();
uint16_t uniffi_lwk_checksum_method_esploraclient_broadcast();
uint16_t uniffi_lwk_checksum_method_esploraclient_full_scan();
uint16_t uniffi_lwk_checksum_method_esploraclient_full_scan_to_index();
uint16_t uniffi_lwk_checksum_method_esploraclient_tip();
uint16_t uniffi_lwk_checksum_method_foreignstore_get();
uint16_t uniffi_lwk_checksum_method_foreignstore_put();
uint16_t uniffi_lwk_checksum_method_foreignstore_remove();
uint16_t uniffi_lwk_checksum_method_invoice_amount_sats();
uint16_t uniffi_lwk_checksum_method_invoice_bolt11_invoice();
uint16_t uniffi_lwk_checksum_method_invoice_bolt12_invoice();
uint16_t uniffi_lwk_checksum_method_invoice_is_bolt11();
uint16_t uniffi_lwk_checksum_method_invoice_is_bolt12();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_advance();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_bolt11_invoice();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_boltz_fee();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_claim_txid();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_complete_pay();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_fee();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_lockup_txid();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_serialize();
uint16_t uniffi_lwk_checksum_method_invoiceresponse_swap_id();
uint16_t uniffi_lwk_checksum_method_issuance_asset();
uint16_t uniffi_lwk_checksum_method_issuance_asset_satoshi();
uint16_t uniffi_lwk_checksum_method_issuance_is_confidential();
uint16_t uniffi_lwk_checksum_method_issuance_is_issuance();
uint16_t uniffi_lwk_checksum_method_issuance_is_null();
uint16_t uniffi_lwk_checksum_method_issuance_is_reissuance();
uint16_t uniffi_lwk_checksum_method_issuance_prev_txid();
uint16_t uniffi_lwk_checksum_method_issuance_prev_vout();
uint16_t uniffi_lwk_checksum_method_issuance_token();
uint16_t uniffi_lwk_checksum_method_issuance_token_satoshi();
uint16_t uniffi_lwk_checksum_method_lightningpayment_bolt11_invoice();
uint16_t uniffi_lwk_checksum_method_lightningpayment_bolt12_invoice_amount();
uint16_t uniffi_lwk_checksum_method_lightningpayment_bolt12_offer_has_amount();
uint16_t uniffi_lwk_checksum_method_lightningpayment_description();
uint16_t uniffi_lwk_checksum_method_lightningpayment_is_bolt12();
uint16_t uniffi_lwk_checksum_method_lightningpayment_set_bolt12_invoice_amount();
uint16_t uniffi_lwk_checksum_method_lightningpayment_set_bolt12_invoice_amount_via_items();
uint16_t uniffi_lwk_checksum_method_lockupresponse_advance();
uint16_t uniffi_lwk_checksum_method_lockupresponse_boltz_fee();
uint16_t uniffi_lwk_checksum_method_lockupresponse_chain_from();
uint16_t uniffi_lwk_checksum_method_lockupresponse_chain_to();
uint16_t uniffi_lwk_checksum_method_lockupresponse_claim_address();
uint16_t uniffi_lwk_checksum_method_lockupresponse_claim_txid();
uint16_t uniffi_lwk_checksum_method_lockupresponse_complete();
uint16_t uniffi_lwk_checksum_method_lockupresponse_expected_amount();
uint16_t uniffi_lwk_checksum_method_lockupresponse_fee();
uint16_t uniffi_lwk_checksum_method_lockupresponse_lockup_address();
uint16_t uniffi_lwk_checksum_method_lockupresponse_lockup_txid();
uint16_t uniffi_lwk_checksum_method_lockupresponse_refund_txid();
uint16_t uniffi_lwk_checksum_method_lockupresponse_serialize();
uint16_t uniffi_lwk_checksum_method_lockupresponse_set_lockup_txid();
uint16_t uniffi_lwk_checksum_method_lockupresponse_swap_id();
uint16_t uniffi_lwk_checksum_method_lockupresponse_uri();
uint16_t uniffi_lwk_checksum_method_logging_log();
uint16_t uniffi_lwk_checksum_method_lwktestenv_electrum_url();
uint16_t uniffi_lwk_checksum_method_lwktestenv_esplora_url();
uint16_t uniffi_lwk_checksum_method_lwktestenv_generate();
uint16_t uniffi_lwk_checksum_method_lwktestenv_genesis_block_hash();
uint16_t uniffi_lwk_checksum_method_lwktestenv_get_new_address();
uint16_t uniffi_lwk_checksum_method_lwktestenv_height();
uint16_t uniffi_lwk_checksum_method_lwktestenv_issue_asset();
uint16_t uniffi_lwk_checksum_method_lwktestenv_network();
uint16_t uniffi_lwk_checksum_method_lwktestenv_send_to_address();
uint16_t uniffi_lwk_checksum_method_lwktestenv_waterfalls_url();
uint16_t uniffi_lwk_checksum_method_lwkteststore_read();
uint16_t uniffi_lwk_checksum_method_lwkteststore_remove();
uint16_t uniffi_lwk_checksum_method_lwkteststore_write();
uint16_t uniffi_lwk_checksum_method_mnemonic_word_count();
uint16_t uniffi_lwk_checksum_method_network_default_electrum_client();
uint16_t uniffi_lwk_checksum_method_network_default_esplora_client();
uint16_t uniffi_lwk_checksum_method_network_genesis_block_hash();
uint16_t uniffi_lwk_checksum_method_network_is_mainnet();
uint16_t uniffi_lwk_checksum_method_network_policy_asset();
uint16_t uniffi_lwk_checksum_method_network_tx_builder();
uint16_t uniffi_lwk_checksum_method_outpoint_txid();
uint16_t uniffi_lwk_checksum_method_outpoint_vout();
uint16_t uniffi_lwk_checksum_method_payment_bip21();
uint16_t uniffi_lwk_checksum_method_payment_bip321();
uint16_t uniffi_lwk_checksum_method_payment_bip353();
uint16_t uniffi_lwk_checksum_method_payment_bitcoin_address();
uint16_t uniffi_lwk_checksum_method_payment_fetch_lnurl_invoice();
uint16_t uniffi_lwk_checksum_method_payment_kind();
uint16_t uniffi_lwk_checksum_method_payment_lightning_invoice();
uint16_t uniffi_lwk_checksum_method_payment_lightning_offer();
uint16_t uniffi_lwk_checksum_method_payment_lightning_payment();
uint16_t uniffi_lwk_checksum_method_payment_liquid_address();
uint16_t uniffi_lwk_checksum_method_payment_liquid_bip21();
uint16_t uniffi_lwk_checksum_method_payment_lnurl();
uint16_t uniffi_lwk_checksum_method_payment_resolve_bip353();
uint16_t uniffi_lwk_checksum_method_payment_resolve_lnurl_info();
uint16_t uniffi_lwk_checksum_method_posconfig_currency();
uint16_t uniffi_lwk_checksum_method_posconfig_descriptor();
uint16_t uniffi_lwk_checksum_method_posconfig_encode();
uint16_t uniffi_lwk_checksum_method_posconfig_show_description();
uint16_t uniffi_lwk_checksum_method_posconfig_show_gear();
uint16_t uniffi_lwk_checksum_method_precision_sats_to_string();
uint16_t uniffi_lwk_checksum_method_precision_string_to_sats();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_advance();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_boltz_fee();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_complete_pay();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_fee();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_lockup_txid();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_refund_txid();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_serialize();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_set_lockup_txid();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_swap_id();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_uri();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_uri_address();
uint16_t uniffi_lwk_checksum_method_preparepayresponse_uri_amount();
uint16_t uniffi_lwk_checksum_method_pset_combine();
uint16_t uniffi_lwk_checksum_method_pset_extract_tx();
uint16_t uniffi_lwk_checksum_method_pset_finalize();
uint16_t uniffi_lwk_checksum_method_pset_inputs();
uint16_t uniffi_lwk_checksum_method_pset_outputs();
uint16_t uniffi_lwk_checksum_method_pset_unique_id();
uint16_t uniffi_lwk_checksum_method_psetbalance_balances();
uint16_t uniffi_lwk_checksum_method_psetbalance_fee();
uint16_t uniffi_lwk_checksum_method_psetbalance_recipients();
uint16_t uniffi_lwk_checksum_method_psetdetails_balance();
uint16_t uniffi_lwk_checksum_method_psetdetails_fingerprints_has();
uint16_t uniffi_lwk_checksum_method_psetdetails_fingerprints_missing();
uint16_t uniffi_lwk_checksum_method_psetdetails_inputs_issuances();
uint16_t uniffi_lwk_checksum_method_psetdetails_signatures();
uint16_t uniffi_lwk_checksum_method_psetinput_issuance();
uint16_t uniffi_lwk_checksum_method_psetinput_issuance_asset();
uint16_t uniffi_lwk_checksum_method_psetinput_issuance_ids();
uint16_t uniffi_lwk_checksum_method_psetinput_issuance_token();
uint16_t uniffi_lwk_checksum_method_psetinput_previous_script_pubkey();
uint16_t uniffi_lwk_checksum_method_psetinput_previous_txid();
uint16_t uniffi_lwk_checksum_method_psetinput_previous_vout();
uint16_t uniffi_lwk_checksum_method_psetinput_redeem_script();
uint16_t uniffi_lwk_checksum_method_psetinput_sighash();
uint16_t uniffi_lwk_checksum_method_psetoutput_amount();
uint16_t uniffi_lwk_checksum_method_psetoutput_asset();
uint16_t uniffi_lwk_checksum_method_psetoutput_blinder_index();
uint16_t uniffi_lwk_checksum_method_psetoutput_script_pubkey();
uint16_t uniffi_lwk_checksum_method_psetsignatures_has_signature();
uint16_t uniffi_lwk_checksum_method_psetsignatures_missing_signature();
uint16_t uniffi_lwk_checksum_method_quotebuilder_build();
uint16_t uniffi_lwk_checksum_method_quotebuilder_receive();
uint16_t uniffi_lwk_checksum_method_quotebuilder_send();
uint16_t uniffi_lwk_checksum_method_recipient_address();
uint16_t uniffi_lwk_checksum_method_recipient_asset();
uint16_t uniffi_lwk_checksum_method_recipient_value();
uint16_t uniffi_lwk_checksum_method_recipient_vout();
uint16_t uniffi_lwk_checksum_method_script_bytes();
uint16_t uniffi_lwk_checksum_method_script_is_provably_unspendable();
uint16_t uniffi_lwk_checksum_method_script_jet_sha256_hex();
uint16_t uniffi_lwk_checksum_method_script_to_asm();
uint16_t uniffi_lwk_checksum_method_script_to_bytes();
uint16_t uniffi_lwk_checksum_method_secretkey_bytes();
uint16_t uniffi_lwk_checksum_method_secretkey_sign();
uint16_t uniffi_lwk_checksum_method_signer_amp0_account_xpub();
uint16_t uniffi_lwk_checksum_method_signer_amp0_sign_challenge();
uint16_t uniffi_lwk_checksum_method_signer_amp0_signer_data();
uint16_t uniffi_lwk_checksum_method_signer_derive_bip85_mnemonic();
uint16_t uniffi_lwk_checksum_method_signer_fingerprint();
uint16_t uniffi_lwk_checksum_method_signer_keyorigin_xpub();
uint16_t uniffi_lwk_checksum_method_signer_mnemonic();
uint16_t uniffi_lwk_checksum_method_signer_sign();
uint16_t uniffi_lwk_checksum_method_signer_singlesig_desc();
uint16_t uniffi_lwk_checksum_method_signer_wpkh_slip77_descriptor();
uint16_t uniffi_lwk_checksum_method_transaction_bytes();
uint16_t uniffi_lwk_checksum_method_transaction_discount_vsize();
uint16_t uniffi_lwk_checksum_method_transaction_fee();
uint16_t uniffi_lwk_checksum_method_transaction_inputs();
uint16_t uniffi_lwk_checksum_method_transaction_outputs();
uint16_t uniffi_lwk_checksum_method_transaction_to_bytes();
uint16_t uniffi_lwk_checksum_method_transaction_txid();
uint16_t uniffi_lwk_checksum_method_transaction_verify_tx_amt_proofs();
uint16_t uniffi_lwk_checksum_method_txbuilder_add_burn();
uint16_t uniffi_lwk_checksum_method_txbuilder_add_explicit_recipient();
uint16_t uniffi_lwk_checksum_method_txbuilder_add_external_utxos();
uint16_t uniffi_lwk_checksum_method_txbuilder_add_input_rangeproofs();
uint16_t uniffi_lwk_checksum_method_txbuilder_add_lbtc_recipient();
uint16_t uniffi_lwk_checksum_method_txbuilder_add_recipient();
uint16_t uniffi_lwk_checksum_method_txbuilder_drain_lbtc_to();
uint16_t uniffi_lwk_checksum_method_txbuilder_drain_lbtc_wallet();
uint16_t uniffi_lwk_checksum_method_txbuilder_fee_rate();
uint16_t uniffi_lwk_checksum_method_txbuilder_finish();
uint16_t uniffi_lwk_checksum_method_txbuilder_finish_for_amp0();
uint16_t uniffi_lwk_checksum_method_txbuilder_issue_asset();
uint16_t uniffi_lwk_checksum_method_txbuilder_liquidex_make();
uint16_t uniffi_lwk_checksum_method_txbuilder_liquidex_take();
uint16_t uniffi_lwk_checksum_method_txbuilder_reissue_asset();
uint16_t uniffi_lwk_checksum_method_txbuilder_set_wallet_utxos();
uint16_t uniffi_lwk_checksum_method_txin_outpoint();
uint16_t uniffi_lwk_checksum_method_txin_sequence();
uint16_t uniffi_lwk_checksum_method_txout_asset();
uint16_t uniffi_lwk_checksum_method_txout_is_fee();
uint16_t uniffi_lwk_checksum_method_txout_is_partially_blinded();
uint16_t uniffi_lwk_checksum_method_txout_script_pubkey();
uint16_t uniffi_lwk_checksum_method_txout_unblind();
uint16_t uniffi_lwk_checksum_method_txout_unconfidential_address();
uint16_t uniffi_lwk_checksum_method_txout_value();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_asset();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_asset_bf();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_asset_commitment();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_is_explicit();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_value();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_value_bf();
uint16_t uniffi_lwk_checksum_method_txoutsecrets_value_commitment();
uint16_t uniffi_lwk_checksum_method_txid_bytes();
uint16_t uniffi_lwk_checksum_method_txid_to_bytes();
uint16_t uniffi_lwk_checksum_method_unvalidatedliquidexproposal_insecure_validate();
uint16_t uniffi_lwk_checksum_method_unvalidatedliquidexproposal_needed_tx();
uint16_t uniffi_lwk_checksum_method_unvalidatedliquidexproposal_validate();
uint16_t uniffi_lwk_checksum_method_update_only_tip();
uint16_t uniffi_lwk_checksum_method_update_serialize();
uint16_t uniffi_lwk_checksum_method_validatedliquidexproposal_input();
uint16_t uniffi_lwk_checksum_method_validatedliquidexproposal_output();
uint16_t uniffi_lwk_checksum_method_valueblindingfactor_to_bytes();
uint16_t uniffi_lwk_checksum_method_wallettx_balance();
uint16_t uniffi_lwk_checksum_method_wallettx_fee();
uint16_t uniffi_lwk_checksum_method_wallettx_height();
uint16_t uniffi_lwk_checksum_method_wallettx_inputs();
uint16_t uniffi_lwk_checksum_method_wallettx_outputs();
uint16_t uniffi_lwk_checksum_method_wallettx_timestamp();
uint16_t uniffi_lwk_checksum_method_wallettx_tx();
uint16_t uniffi_lwk_checksum_method_wallettx_txid();
uint16_t uniffi_lwk_checksum_method_wallettx_type_();
uint16_t uniffi_lwk_checksum_method_wallettx_unblinded_url();
uint16_t uniffi_lwk_checksum_method_wallettxout_address();
uint16_t uniffi_lwk_checksum_method_wallettxout_ext_int();
uint16_t uniffi_lwk_checksum_method_wallettxout_height();
uint16_t uniffi_lwk_checksum_method_wallettxout_outpoint();
uint16_t uniffi_lwk_checksum_method_wallettxout_script_pubkey();
uint16_t uniffi_lwk_checksum_method_wallettxout_unblinded();
uint16_t uniffi_lwk_checksum_method_wallettxout_wildcard_index();
uint16_t uniffi_lwk_checksum_method_wollet_add_details();
uint16_t uniffi_lwk_checksum_method_wollet_address();
uint16_t uniffi_lwk_checksum_method_wollet_apply_transaction();
uint16_t uniffi_lwk_checksum_method_wollet_apply_update();
uint16_t uniffi_lwk_checksum_method_wollet_balance();
uint16_t uniffi_lwk_checksum_method_wollet_descriptor();
uint16_t uniffi_lwk_checksum_method_wollet_dwid();
uint16_t uniffi_lwk_checksum_method_wollet_extract_wallet_utxos();
uint16_t uniffi_lwk_checksum_method_wollet_finalize();
uint16_t uniffi_lwk_checksum_method_wollet_is_amp0();
uint16_t uniffi_lwk_checksum_method_wollet_is_segwit();
uint16_t uniffi_lwk_checksum_method_wollet_max_weight_to_satisfy();
uint16_t uniffi_lwk_checksum_method_wollet_pset_details();
uint16_t uniffi_lwk_checksum_method_wollet_transaction();
uint16_t uniffi_lwk_checksum_method_wollet_transactions();
uint16_t uniffi_lwk_checksum_method_wollet_transactions_paginated();
uint16_t uniffi_lwk_checksum_method_wollet_txos();
uint16_t uniffi_lwk_checksum_method_wollet_unblind_utxos_with();
uint16_t uniffi_lwk_checksum_method_wollet_utxos();
uint16_t uniffi_lwk_checksum_method_wollet_wait_for_tx();
uint16_t uniffi_lwk_checksum_method_wolletbuilder_build();
uint16_t uniffi_lwk_checksum_method_wolletbuilder_utxo_only();
uint16_t uniffi_lwk_checksum_method_wolletbuilder_with_legacy_fs_store();
uint16_t uniffi_lwk_checksum_method_wolletbuilder_with_merge_threshold();
uint16_t uniffi_lwk_checksum_method_wolletdescriptor_derive_blinding_key();
uint16_t uniffi_lwk_checksum_method_wolletdescriptor_is_amp0();
uint16_t uniffi_lwk_checksum_method_wolletdescriptor_is_mainnet();
uint16_t uniffi_lwk_checksum_method_wolletdescriptor_script_pubkey();
uint16_t uniffi_lwk_checksum_method_wolletdescriptor_url_encoded_descriptor();
uint16_t uniffi_lwk_checksum_constructor_address_new();
uint16_t uniffi_lwk_checksum_constructor_amp0_new();
uint16_t uniffi_lwk_checksum_constructor_amp0connected_new();
uint16_t uniffi_lwk_checksum_constructor_amp0pset_new();
uint16_t uniffi_lwk_checksum_constructor_amp2_new();
uint16_t uniffi_lwk_checksum_constructor_amp2_new_testnet();
uint16_t uniffi_lwk_checksum_constructor_anyclient_from_electrum();
uint16_t uniffi_lwk_checksum_constructor_anyclient_from_esplora();
uint16_t uniffi_lwk_checksum_constructor_assetblindingfactor_from_bytes();
uint16_t uniffi_lwk_checksum_constructor_assetblindingfactor_from_string();
uint16_t uniffi_lwk_checksum_constructor_assetblindingfactor_zero();
uint16_t uniffi_lwk_checksum_constructor_bip_new_bip49();
uint16_t uniffi_lwk_checksum_constructor_bip_new_bip84();
uint16_t uniffi_lwk_checksum_constructor_bip_new_bip87();
uint16_t uniffi_lwk_checksum_constructor_bip21_new();
uint16_t uniffi_lwk_checksum_constructor_bip321_new();
uint16_t uniffi_lwk_checksum_constructor_bitcoinaddress_new();
uint16_t uniffi_lwk_checksum_constructor_bolt11invoice_new();
uint16_t uniffi_lwk_checksum_constructor_boltzsession_from_builder();
uint16_t uniffi_lwk_checksum_constructor_boltzsession_new();
uint16_t uniffi_lwk_checksum_constructor_contract_new();
uint16_t uniffi_lwk_checksum_constructor_currencycode_new();
uint16_t uniffi_lwk_checksum_constructor_electrumclient_from_url();
uint16_t uniffi_lwk_checksum_constructor_electrumclient_new();
uint16_t uniffi_lwk_checksum_constructor_esploraclient_from_builder();
uint16_t uniffi_lwk_checksum_constructor_esploraclient_new();
uint16_t uniffi_lwk_checksum_constructor_esploraclient_new_waterfalls();
uint16_t uniffi_lwk_checksum_constructor_externalutxo_from_unchecked_data();
uint16_t uniffi_lwk_checksum_constructor_externalutxo_new();
uint16_t uniffi_lwk_checksum_constructor_foreignstorelink_new();
uint16_t uniffi_lwk_checksum_constructor_lightningpayment_from_bolt11_invoice();
uint16_t uniffi_lwk_checksum_constructor_lightningpayment_new();
uint16_t uniffi_lwk_checksum_constructor_logginglink_new();
uint16_t uniffi_lwk_checksum_constructor_lwktestenv_new();
uint16_t uniffi_lwk_checksum_constructor_lwkteststore_new();
uint16_t uniffi_lwk_checksum_constructor_mnemonic_from_entropy();
uint16_t uniffi_lwk_checksum_constructor_mnemonic_from_random();
uint16_t uniffi_lwk_checksum_constructor_mnemonic_new();
uint16_t uniffi_lwk_checksum_constructor_network_mainnet();
uint16_t uniffi_lwk_checksum_constructor_network_regtest();
uint16_t uniffi_lwk_checksum_constructor_network_regtest_default();
uint16_t uniffi_lwk_checksum_constructor_network_testnet();
uint16_t uniffi_lwk_checksum_constructor_outpoint_from_parts();
uint16_t uniffi_lwk_checksum_constructor_outpoint_new();
uint16_t uniffi_lwk_checksum_constructor_payment_new();
uint16_t uniffi_lwk_checksum_constructor_posconfig_decode();
uint16_t uniffi_lwk_checksum_constructor_posconfig_new();
uint16_t uniffi_lwk_checksum_constructor_posconfig_with_options();
uint16_t uniffi_lwk_checksum_constructor_precision_new();
uint16_t uniffi_lwk_checksum_constructor_pset_new();
uint16_t uniffi_lwk_checksum_constructor_script_empty();
uint16_t uniffi_lwk_checksum_constructor_script_from_bytes();
uint16_t uniffi_lwk_checksum_constructor_script_from_string();
uint16_t uniffi_lwk_checksum_constructor_script_new();
uint16_t uniffi_lwk_checksum_constructor_script_new_op_return();
uint16_t uniffi_lwk_checksum_constructor_secretkey_from_bytes();
uint16_t uniffi_lwk_checksum_constructor_secretkey_from_wif();
uint16_t uniffi_lwk_checksum_constructor_signer_new();
uint16_t uniffi_lwk_checksum_constructor_signer_random();
uint16_t uniffi_lwk_checksum_constructor_transaction_from_bytes();
uint16_t uniffi_lwk_checksum_constructor_transaction_from_string();
uint16_t uniffi_lwk_checksum_constructor_transaction_new();
uint16_t uniffi_lwk_checksum_constructor_txbuilder_new();
uint16_t uniffi_lwk_checksum_constructor_txout_from_explicit();
uint16_t uniffi_lwk_checksum_constructor_txid_from_bytes();
uint16_t uniffi_lwk_checksum_constructor_txid_from_string();
uint16_t uniffi_lwk_checksum_constructor_txid_new();
uint16_t uniffi_lwk_checksum_constructor_unvalidatedliquidexproposal_from_pset();
uint16_t uniffi_lwk_checksum_constructor_unvalidatedliquidexproposal_new();
uint16_t uniffi_lwk_checksum_constructor_update_new();
uint16_t uniffi_lwk_checksum_constructor_valueblindingfactor_from_bytes();
uint16_t uniffi_lwk_checksum_constructor_valueblindingfactor_from_string();
uint16_t uniffi_lwk_checksum_constructor_valueblindingfactor_zero();
uint16_t uniffi_lwk_checksum_constructor_webhook_new();
uint16_t uniffi_lwk_checksum_constructor_wollet_new();
uint16_t uniffi_lwk_checksum_constructor_wollet_with_custom_store();
uint16_t uniffi_lwk_checksum_constructor_wolletbuilder_new();
uint16_t uniffi_lwk_checksum_constructor_wolletdescriptor_new();
uint32_t ffi_lwk_uniffi_contract_version();
#ifdef __cplusplus
}
#endif