package:build:
  tags:
    - garelease
  stage: package
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    paths:
    - $CI_PROJECT_DIR/dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - rm -fr dist
    - mkdir dist
    - mv BlockstreamSetup.exe dist/BlockstreamSetup-x86_64.exe
    - mv "macos-arm64/Blockstream.dmg" dist/Blockstream-arm64.dmg
    - mv "macos-x86_64/Blockstream.dmg" dist/Blockstream-x86_64.dmg
    - mv "macos-universal/Blockstream.dmg" dist/Blockstream-universal.dmg
    - chmod +x blockstream
    - tar czf dist/Blockstream-linux-x86_64.tar.gz -C . blockstream
    - cp Blockstream-x86_64.AppImage dist
    - chmod +x dist/Blockstream-x86_64.AppImage
    - cd dist
    - /opt/process_release
    - cat SHA256SUMS.asc
  needs:
    - linux-x86_64:build-appimage
    - linux-x86_64:build-binary
    - macos-arm64:staple
    - macos-x86_64:staple
    - macos-universal:staple
    - windows-x86_64:sign-installer

.publish:
  tags:
    - ga
  stage: package
  when: manual
  needs: ["package:build"]
  image: glregistry.blockstream.io/blockstream/p/gcloud-docker:tf0.15.4
  script:
    - cd dist
    - ../tools/publish.sh

package:publish-rc:
  extends:
    - .publish
  variables:
    CHANNEL: rc

package:publish-latest:
  extends:
    - .publish
  variables:
    CHANNEL: latest
  only:
    - tags
  except:
    - branches
