set(BLOCKSTREAM_PROJECT_NAME "blockstream")
set(BLOCKSTREAM_VERSION "3.5.1")
set(BLOCKSTREAM_DISPLAY_NAME "Blockstream")
set(BLOCKSTREAM_VENDOR "Blockstream")
set(BLOCKSTREAM_DESCRIPTION "Non-custodial Bitcoin wallet desktop application")
set(BLOCKSTREAM_HOMEPAGE_URL "https://blockstream.com/app/")
